[package]
name = "mandelbrot_32"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
clap = { version = "4.5.57", features = ["derive"] }
env_logger = "0.11.8"
pollster = "0.4.0"
wgpu = "28.0.0"
winit = "0.30.12"
